### ISSUE TITLE
Pagination for big amounts of data

### ISSUE THREAD

**Issue by markus-moser** [pimcore/generic-data-index-bundle#129]
In the studio UI backend the pagination will look similar to the current classic UI:

![image](https://github.com/pimcore/generic-data-index-bundle/assets/4639428/359fb5db-c6b3-4672-94ed-86bf18bb721c)

OpenSearch by default has a limit of 10.000 for the offset of a search result. So pagination for pages after this limit will fail (unless not changed in the index configuration).

Therefore we need to somehow tackle this problem. I think the best solution might be to somehow inverse the sort direction for the pages at the end - so when jumping to the last page of a search result in ascending order would result on the first page in descending order. With this approach and the default limit it would be possible to page over 20.000 items. The result array would be needed to be flipped afterwards.

With this approach we would only get a problem for pages in the middle. For those pages we could use the scroll API, but unfortunately it's not possible to directly jump to a page with it (and also the performance would be a real problem). So there is no real solution for this case. I think the best approach would be to really show a error message to the user in this case and maybe play arround a little bit with the `max_result_window` setting if it is safe to increase it a little bit.

**Comment by herbertroth** [comment]
I recommend using search_after for all pagination scenarios and avoiding from altogether. The from parameter does not scale well and can lead to performance issues with large result sets. To support reliable and efficient pagination, every query should include a defined sort order, which is required for search_after to work correctly.
Even for smaller result sets, using search_after ensures consistency and prepares the system for scaling. For large exports, the Scroll API remains the preferred approach.

**Comment by markus-moser** [comment]
@herbertroth Yes, in general I agree but the problem with search_after is that it's not possible to directly jump to a defined page number. It's more like a "next page" approach. Do you know a solution for this?

**Comment by herbertroth** [comment]
@markus-moser I don't know a solution for this. But what is a meaningful use case to page over hundreds of pages? It takes ages to find something, if ever. So maybe limit paging at all to a use full amount of pages solves this "problem" in a better way. It's more a usability topic than a technical one.

**Comment by markus-moser** [comment]
@herbertroth Yes, but the problem is that our UI supports paging like that - also historically from the classic bundle. Jumping for example to the last page is helpful in various scenarios. We would need to do a quite drastic change in the UI and we would need to start in the design phase again for the pagination.

I found this:
https://www.linkedin.com/pulse/effective-pagination-elasticsearch-swaroop-gupta-b-a/

But I don't know if skipping the source field really helps that much.

**Comment by herbertroth** [comment]
@markus-moser "Yes, but the problem is that our UI supports paging like that" i agree thats the problem. We should solve it in a way that we do it better this time and do NOT support this at all. Where are the limits to this? paging over 1mio items 10 mio? We know this will lead to performance problems we cant solve, because of general limitations of from. If you need to "find" something in a that large data set use search or filter and not page. Jumping to the last page should be easy, just revert sort. So maybe paging to the first 25(or something like this) pages and offer last page in addition can do the job.
