### ISSUE TITLE
Index not found: pimcore_data_object_folders

### ISSUE THREAD

**Issue by morgannilsson** [pimcore/generic-data-index-bundle#162]
We use Pimcore 2024.1 with "pimcore/generic-data-index-bundle": v1.0.5

When saving a DataObject folder in Pimcore Admin we get "no such index [pimcore_data_object_folders]"

The error comes from:

https://github.com/pimcore/generic-data-index-bundle/blob/v1.0.5/src/Service/SearchIndex/IndexService/ElementTypeAdapter/DataObjectTypeAdapter.php#L68

When should this index be created? 
Now I have to create it manually.

**Comment by fashxp** [comment]
did you execute that command: https://pimcore.com/docs/platform/Generic_Data_Index/Installation/#commands-after-installation

**Comment by markus-moser** [comment]
This is a bug. It's already fixed in the 4.x branch where folder indexing works without a problem. I will backport the fix to 1.0.6.

**Comment by morgannilsson** [comment]
Ok, great. 

Yeah, sorry. I did follow the installation procedure on https://pimcore.com/docs/platform/Generic_Data_Index/Installation/#commands-after-installation

My quick solution was to `curl -X PUT http://localhost:9200/pimcore_data_object_folders` to avoid all warning messages about missing index.

**Comment by markus-moser** [comment]
I decided to skip data object folder indexing for version 1.0.x (see #168) as the whole data object folder index and search is more like a new feature in 1.1. Data object folder search is not relevant for the portal engine (which is currently the only released usage of the generic data index bundle). If you already have usecases for searching for data object folders, please use version 1.1.0 of the generic data index bundle which will be released very soon (hopefully next week).
