### ISSUE TITLE
Index Updating should figure that an index already exists

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/generic-data-index-bundle#165]
When I run `generic-data-index:update:index` I run into the following issue:

```
18:38:11 WARNING   [pimcore.opensearch.default] Response ["{"error":{"root_cause":[{"type":"invalid_alias_name_exception","reason":"Invalid alias name [pimcore_asset], an index exists with the same name as the alias","index":"pimcore_asset","index_uuid":"5Pps5u8oSV2MgY2NaIeKww"}],"type":"invalid_alias_name_exception","reason":"Invalid alias name [pimcore_asset], an index exists with the same name as the alias","index":"pimcore_asset","index_uuid":"5Pps5u8oSV2MgY2NaIeKww"},"status":400}"]
```

When an index already exists, there should be an option to delete it or that the bundle uses that index and updates it. Or is there already and I just missed it?

**Comment by markus-moser** [comment]
I had the same problem several times. The problem there is the `auto_create_index` feature of OpenSearch. When you already save elements and run the queue before the index is created (so the `bin/console generic-data-index:update:index` command was executed OpenSearch will implicitly create the index with the default detected automatic mapping. The problem then is that in the case of the generic data index `pimcore_asset` is an index alias and no real index, therefore the command will not recreate it.

The best way to avoid this is to disable the auto mapping feature - see:
https://github.com/pimcore/demo-enterprise/blob/2024.x/docker-compose.yaml#L81

But I agree that we should somehow automatically detect this case and provide a option to delete this index automatically.

**Comment by dpfaffenbauer** [comment]
I don't have access to that docker compose file and that repo. can you paste the config for opensearch here please?

**Comment by markus-moser** [comment]
`  - action.auto_create_index=false`

![image](https://github.com/user-attachments/assets/d14ad9f3-c462-4b53-833b-5e78ec92bbe3)
