### ISSUE TITLE
[Improvement] Add Elasticsearch support

### ISSUE THREAD

**Issue by solverat** [pimcore/generic-data-index-bundle#207]
Maybe more a discussion topic than a real issue. However:

## Statement
> [D.N.A] Elasticsearch and Kibana can be called Open Source again. 
> – https://www.elastic.co/de/blog/elasticsearch-is-open-source-again

The generic data index bundle will be a must-have or even a required bundle within the pimcore ecosystem (sooner or later) and therefor we need to make sure that we are backing the right horse.

Personally, I have no real opinion on that. But since this decision is bounded to a lot of dependencies (Server-Infrastructure/DevOps, FE-Application using search engines), an official statement from PIMCORE would be awesome!

**Comment by fashxp** [comment]
Thx for sharing and opening the discussion!
For now, our plan is to stay on Opensearch.
We will check though, if support of both engines (opensearch, elasticsearch) would be possible with decent efforts and feasible.

Happy to read additional aspects and/or thoughts on this.

**Comment by jdreesen** [comment]
So support for both is not planned?

In our company we use Elasticsearch a lot, and switching is not easy because everything depends on https://github.com/ruflin/Elastica/, which doesn't (and probably will not) support Opensearch. This means that we would have to use *both* in the future, which is quite unfortunate.

**Comment by fashxp** [comment]
Not yet, and this also heavily depends on how Elasticsearch and Opensearch will develop in future. 
Right now, supporting both might be possible. But what, when they develop in different directions and are not compatible with each other anymore.

We also need to balance our resources and prioritize. If someone is willing and ready to contribute and maintain support for Elasticsearch, please let us know.

**Comment by NiklasBr** [comment]
We also have a lot of things which are *not* compatible with Opensearch and cannot move to it in the future. For example Pimcore still requires Elasticsearch in the E-commerce Framework Bundle:

https://github.com/pimcore/ecommerce-framework-bundle/blob/67e3b0e757c3e36b7929899cf2a588399afcbca8/composer.json#L26-L38 

I vote to drop Opensearch in favour of restoring Elasticsearch.

**Comment by fashxp** [comment]
Opensearch support for E-Commerce Framework is planned until end of this year, will be shipped with 2024.4.

**Comment by fashxp** [comment]
https://www.elastic.co/events/elasticon/munich ... AWS is sponsoring an elastic event 🤔.

**Comment by fashxp** [comment]
Update: 
We further investigate to support Elasticsearch and Opensearch in parallel - for now. And it looks promising so far. 

This buys us some time and we can monitor how the situation evolves. At some point, when the two technologies diverge too much, we will need to decide for one technology though.

**Comment by lukmzig** [comment]
Should be now resolved by https://github.com/pimcore/generic-data-index-bundle/pull/239
