### ISSUE TITLE
Data object search result item index needs to be nullable

### ISSUE THREAD

**Issue by markus-moser** [pimcore/generic-data-index-bundle#214]
For folders we do not have an index and therefore the attribute needs to be nullable:

![image](https://github.com/user-attachments/assets/1b7f79b1-94ad-47e2-9ba5-bcd5a72999ca)

**Comment by lukmzig** [comment]
@markus-moser hmmm I had a look and for me the index is always 0 if not set
also in the core models it does not seem to be nullable?
https://github.com/pimcore/pimcore/blob/11.x/models/DataObject/AbstractObject.php#L780

https://github.com/pimcore/pimcore/blob/11.x/models/DataObject/AbstractObject.php#L813

and in the DB properties seems like by default is 0 as well
![image](https://github.com/user-attachments/assets/f99a5e3c-acc8-4b13-9751-1504e45e3120)


can you please double check? Maybe I am missing something

**Comment by markus-moser** [comment]
@lukmzig You are right, sorry! After re-indexing everything again it works now!
