### ISSUE TITLE
Wrong shortcut on generic-data-index:update:index

### ISSUE THREAD

**Issue by morgannilsson** [pimcore/generic-data-index-bundle#236]
->setName('generic-data-index:update:index')
            ->addOption(
                self::OPTION_CLASS_DEFINITION_ID,
                'cid',

```
% console generic-data-index:update:index -v -r -cid=document 

In ArgvInput.php line 125:
                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "-c" option does not exist.   
```

**Comment by lukmzig** [comment]
@morgannilsson thank you for reporting this issue. Should be resolved by #242
`bin/console generic-data-index:update:index -r -c<CLASS_DEFINITION_ID> `
