### ISSUE TITLE
Same index name on document and dataObject: document

### ISSUE THREAD

**Issue by morgannilsson** [pimcore/generic-data-index-bundle#237]
Question:

I just noticed that we have the same index name: pimcore_document on both Documents and our DataObject class: Document.
The Opensearch documents differ with "elementType": "document", vs "elementType": "dataObject". The id is not unique either between Documents and DataObjects?

So document, asset and data-object-folder are reserved words, not to used for DataObjects?

**Comment by fashxp** [comment]
see https://github.com/pimcore/generic-data-index-bundle/pull/229 ... will be fixed in 2.0.0.

**Comment by morgannilsson** [comment]
Ah, I did not look at the merged issues. No backport for 1.2.2 is planned?

**Comment by fashxp** [comment]
it is not possible, as it would be a change of index name aka a bc break.
