### ISSUE TITLE
[Task] Reenable roave/securit

### ISSUE THREAD

**Issue by markus-moser** [pimcore/generic-data-index-bundle#268]
Disabled it with #267 

See also #213

**Comment by jdreesen** [comment]
This just got merged: https://github.com/Roave/SecurityAdvisoriesBuilder/pull/756
So I think you can reenable it soon.

**Comment by markus-moser** [comment]
Thanks for the hint

**Comment by jdreesen** [comment]
Now there is the commit that reverts it: https://github.com/Roave/SecurityAdvisories/commit/d63bf61e4925002df49bcec7043f7c821084c365

**Comment by markus-moser** [comment]
Re-enabled it again in #267
